DROP TABLE IF EXISTS hospital;

CREATE TABLE IF NOT EXISTS hospital (
    num SERIAL PRIMARY KEY,
    live VARCHAR(5) NOT NULL,
	hosp VARCHAR(30) NOT NULL UNIQUE,
	tel VARCHAR(15),
	telnum VARCHAR(7) ,
	people VARCHAR(7),
	address VARCHAR(50) 
  	);